spring:
  application:
    name: hrms-service
  datasource:
    url: ${HRMS_DB_URL:jdbc:postgresql://localhost:5432/fawnix_hrms}
    username: ${HRMS_DB_USERNAME:postgres}
    password: ${HRMS_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
