package com.fawnix.identity.auth.entity;

public enum RoleName {
  ROLE_ADMIN,
  ROLE_SALES_MANAGER,
  ROLE_SALES_REP,
  ROLE_VIEWER,
  ROLE_HR_MANAGER,
  ROLE_RECRUITER,
  ROLE_HIRING_MANAGER,
  ROLE_INTERVIEWER,
  ROLE_EMPLOYEE
}
