spring:
  application:
    name: identity-service
  datasource:
    url: ${IDENTITY_DB_URL:jdbc:postgresql://localhost:5432/fawnix_identity}
    username: ${IDENTITY_DB_USERNAME:postgres}
    password: ${IDENTITY_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    allowed-origins:
      - ${FRONTEND_ORIGIN:http://localhost:5173}
      - http://127.0.0.1:5173
      - http://localhost:5173
      - https://fawnixverse.acstechnologies.co.in
      - http://54.76.187.129
      - https://54.76.187.129
  security:
    jwt:
      issuer: fawnix-verse
      access-token-expiration-minutes: 30
      refresh-token-expiration-days: 14
      secret: ${JWT_SECRET:change-this-local-dev-secret-change-this-local-dev-secret}
    dev-admin-email: ${DEV_ADMIN_EMAIL:admin@fawnix.com}
    dev-admin-password: ${DEV_ADMIN_PASSWORD:Admin@123}
    internal-service-secret: ${INTERNAL_SERVICE_SECRET:fawnix-internal-secret}
