import { addDays, format } from 'date-fns'
import type { Priority, Project, ProjectStatus, ProjectType, DeadlineType, SprintDuration, MemberRole, RolePermission } from './types'

export const priorities: Priority[] = ['Low', 'Medium', 'High', 'Critical']

export const statuses: ProjectStatus[] = [
  'Draft',
  'Planning',
  'Approval Pending',
  'Returned',
  'Rejected',
  'Planned',
  'In Progress',
  'Delayed',
  'Active',
  'On Hold',
  'At Risk',
  'Closure Pending',
  'Completed',
  'Cancelled',
]

export const projectTypes: ProjectType[] = [
  'Web Application',
  'Mobile Application',
  'Desktop Application',
  'IoT Project',
  'AI/ML Project',
  'API Development',
  'Internal Tool',
  'Client Project',
  'Maintenance Project',
  'Research Project',
]

export const deadlineTypes: DeadlineType[] = ['Flexible', 'Fixed Deadline', 'Urgent Delivery']

export const sprintDurations: SprintDuration[] = ['1 Week', '2 Weeks', '3 Weeks', 'Monthly']

export const memberRoles: MemberRole[] = [
  'Project Manager',
  'Team Lead',
  'Developer',
  'QA Engineer',
  'UI/UX Designer',
  'DevOps Engineer',
  'Business Analyst',
  'Stakeholder',
]

export const allRolePermissions: { key: RolePermission; label: string }[] = [
  { key: 'view_project',   label: 'View Project'   },
  { key: 'create_task',    label: 'Create Task'    },
  { key: 'assign_task',    label: 'Assign Task'    },
  { key: 'edit_task',      label: 'Edit Task'      },
  { key: 'delete_task',    label: 'Delete Task'    },
  { key: 'upload_files',   label: 'Upload Files'   },
  { key: 'approve_release',label: 'Approve Release'},
]

export const defaultPermissionsForRole: Record<MemberRole, RolePermission[]> = {
  'Project Manager':   ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'],
  'Team Lead':         ['view_project','create_task','assign_task','edit_task','upload_files','approve_release'],
  'Developer':         ['view_project','create_task','edit_task','upload_files'],
  'QA Engineer':       ['view_project','create_task','edit_task','upload_files'],
  'UI/UX Designer':    ['view_project','create_task','edit_task','upload_files'],
  'DevOps Engineer':   ['view_project','edit_task','upload_files','approve_release'],
  'Business Analyst':  ['view_project','create_task','upload_files'],
  'Stakeholder':       ['view_project'],
}

export const techFrontend = ['React','Angular','Vue','Flutter','Android','iOS','Next.js','Svelte']
export const techBackend  = ['Spring Boot','Node JS','FastAPI','.NET','Django','Laravel','Go','Ruby on Rails']
export const techDatabase = ['PostgreSQL','MySQL','MongoDB','Oracle','Redis','SQLite','Cassandra']
export const techOther    = ['Docker','Kubernetes','AWS','Azure','GCP','Firebase','Terraform','Jenkins']

export const branchStrategies = ['main / develop / feature/*','Git Flow','Trunk Based','GitHub Flow']

export const departments = ['Sales', 'Operations', 'Finance', 'HR', 'IT', 'Support']

export const owners = ['Ananya Rao', 'David Kim', 'Meera Iyer', 'Omar Khan', 'Priya Shah']

export const projectTemplates = [
  'Blank Project',
  'Implementation',
  'Marketing Campaign',
  'Product Launch',
  'Internal Operations',
]

export const projectCategories = [
  'Client Delivery',
  'Internal',
  'Product',
  'Operations',
  'Compliance',
]

export const departmentTeamMembers: Record<string, string[]> = {
  Sales: ['Ananya Rao', 'David Kim', 'Riya Menon', 'James Lee', 'Neha Kapoor'],
  Operations: ['Meera Iyer', 'Omar Khan', 'Kabir Das', 'Luis Martin', 'Fatima Noor'],
  Finance: ['Priya Shah', 'Meera Iyer', 'Nikhil Jain', 'Sara Thomas', 'Arjun Nair'],
  HR: ['Priya Shah', 'Omar Khan', 'Riya Menon', 'Elena Morris', 'Naveen Kumar'],
  IT: ['David Kim', 'Ananya Rao', 'Fatima Noor', 'Luis Martin', 'Nikhil Jain'],
  Support: ['Omar Khan', 'James Lee', 'Sara Thomas', 'Neha Kapoor', 'Kabir Das'],
}

export const today = new Date()

export const storageKey = 'erp-project-management-projects'

const emptyTechStack = { frontend: [], backend: [], database: [], other: [] }
const emptyRepo = { gitUrl: '', branchStrategy: '', devUrl: '', testingUrl: '', productionUrl: '' }
const emptyCommunication = { slackChannel: '', teamsChannel: '', meetingLink: '', reportingFrequency: 'Weekly' as const }

export const seedProjects: Project[] = [
  {
    id: 'proj-001',
    projectCode: 'CRM-2401',
    name: 'CRM Renewal Workspace',
    description:
      'Modernize account visibility, customer ownership, and renewal planning across the sales organization.',
    projectType: 'Client Project',
    projectTemplate: 'Implementation',
    projectCategory: 'Client Delivery',
    tags: ['crm', 'renewal', 'sales'],
    clientName: 'Rachel Morgan',
    clientCompany: 'Northstar Retail',
    clientEmail: 'rachel.morgan@northstar.example',
    clientPhone: '+1 555 014 2201',
    clientLocation: 'New York, USA',
    projectOwner: 'Ananya Rao',
    stakeholders: ['David Kim', 'Riya Menon'],
    deadlineType: 'Fixed Deadline',
    budget: 125000,
    developmentCost: 80000,
    resourceCost: 30000,
    department: 'Sales',
    owner: 'Ananya Rao',
    manager: 'David Kim',
    startDate: format(addDays(today, -42), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 21), 'yyyy-MM-dd'),
    priority: 'High',
    status: 'In Progress',
    approvalRequired: true,
    approvalStatus: 'Approved',
    closureApprovalRequired: true,
    closureStatus: 'Not Required',
    progress: 68,
    teamMembers: ['Ananya Rao', 'David Kim', 'Riya Menon', 'James Lee'],
    team: [
      { name: 'David Kim', role: 'Project Manager', permissions: ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'] },
      { name: 'Riya Menon', role: 'Developer', permissions: ['view_project','create_task','edit_task','upload_files'] },
      { name: 'James Lee', role: 'QA Engineer', permissions: ['view_project','create_task','edit_task','upload_files'] },
    ],
    techStack: { frontend: ['React'], backend: ['Spring Boot'], database: ['PostgreSQL'], other: ['Docker','AWS'] },
    repository: { gitUrl: 'https://github.com/org/crm-renewal', branchStrategy: 'Git Flow', devUrl: '', testingUrl: '', productionUrl: '' },
    modules: [],
    sprints: [],
    risks: [],
    communication: emptyCommunication,
    tasks: [],
    requirementDocument: {
      id: 'req-001',
      name: 'crm-renewal-requirements.pdf',
      type: 'PDF',
      size: '2.4 MB',
      uploadedBy: 'Ananya Rao',
      uploadedAt: format(addDays(today, -38), 'yyyy-MM-dd'),
    },
    notes: 'Renewal reporting is stable. Final approval workflow is pending.',
    comments: [
      {
        id: 'com-001',
        author: 'David Kim',
        message: 'Please keep the renewal dashboard screenshots attached for steering review.',
        date: format(addDays(today, -3), 'yyyy-MM-dd'),
      },
    ],
    attachments: [
      {
        id: 'att-001',
        name: 'renewal-scope.pdf',
        type: 'PDF',
        size: '1.8 MB',
        uploadedBy: 'Ananya Rao',
        uploadedAt: format(addDays(today, -31), 'yyyy-MM-dd'),
      },
    ],
    milestones: [
      {
        id: 'ms-001',
        title: 'Data migration validation',
        dueDate: format(addDays(today, -8), 'yyyy-MM-dd'),
        status: 'Done',
        approvalRequired: false,
        approvalStatus: 'Not Required',
      },
      {
        id: 'ms-002',
        title: 'Manager approval workflow',
        dueDate: format(addDays(today, 12), 'yyyy-MM-dd'),
        status: 'In Progress',
        approvalRequired: true,
        approvalStatus: 'Not Required',
      },
    ],
    activityHistory: [
      {
        id: 'act-001',
        message: 'Progress updated to 68%',
        actor: 'David Kim',
        date: format(addDays(today, -2), 'yyyy-MM-dd'),
      },
      {
        id: 'act-002',
        message: 'Project moved to Active',
        actor: 'Ananya Rao',
        date: format(addDays(today, -19), 'yyyy-MM-dd'),
      },
    ],
  },
  {
    id: 'proj-002',
    projectCode: 'OPS-1188',
    name: 'Warehouse Dispatch Optimization',
    description:
      'Improve dispatch visibility, daily handoff planning, and escalation tracking for regional warehouse teams.',
    projectType: 'Internal Tool',
    projectTemplate: 'Internal Operations',
    projectCategory: 'Operations',
    tags: ['warehouse', 'dispatch', 'logistics'],
    clientName: 'Vikram Patel',
    clientCompany: 'MetroLink Logistics',
    clientEmail: 'vikram.patel@metrolink.example',
    clientPhone: '+1 555 018 7640',
    clientLocation: 'Chicago, USA',
    projectOwner: 'Meera Iyer',
    stakeholders: [],
    deadlineType: 'Fixed Deadline',
    budget: 210000,
    developmentCost: 140000,
    resourceCost: 50000,
    department: 'Operations',
    owner: 'Meera Iyer',
    manager: 'Omar Khan',
    startDate: format(addDays(today, -65), 'yyyy-MM-dd'),
    endDate: format(addDays(today, -4), 'yyyy-MM-dd'),
    priority: 'Critical',
    status: 'At Risk',
    approvalRequired: false,
    approvalStatus: 'Not Required',
    closureApprovalRequired: true,
    closureStatus: 'Not Required',
    progress: 74,
    teamMembers: ['Meera Iyer', 'Omar Khan', 'Kabir Das'],
    team: [
      { name: 'Omar Khan', role: 'Project Manager', permissions: ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'] },
      { name: 'Kabir Das', role: 'Developer', permissions: ['view_project','create_task','edit_task','upload_files'] },
    ],
    techStack: emptyTechStack,
    repository: emptyRepo,
    modules: [],
    sprints: [],
    risks: [{ id: 'risk-001', name: 'Carrier integration delay', level: 'High', impact: 'Dashboard rollout blocked', solution: 'Escalate to leadership' }],
    communication: emptyCommunication,
    tasks: [],
    requirementDocument: null,
    notes: 'Carrier exception handling needs leadership review.',
    comments: [
      {
        id: 'com-002',
        author: 'Meera Iyer',
        message: 'Carrier exception owners need to confirm revised dates.',
        date: format(addDays(today, -5), 'yyyy-MM-dd'),
      },
    ],
    attachments: [
      {
        id: 'att-002',
        name: 'dispatch-risk-log.xlsx',
        type: 'Spreadsheet',
        size: '940 KB',
        uploadedBy: 'Omar Khan',
        uploadedAt: format(addDays(today, -6), 'yyyy-MM-dd'),
      },
    ],
    milestones: [
      {
        id: 'ms-003',
        title: 'Pilot warehouse readiness',
        dueDate: format(addDays(today, -11), 'yyyy-MM-dd'),
        status: 'Done',
        approvalRequired: false,
        approvalStatus: 'Not Required',
      },
      {
        id: 'ms-004',
        title: 'Exception dashboard rollout',
        dueDate: format(addDays(today, -4), 'yyyy-MM-dd'),
        status: 'Delayed',
        approvalRequired: true,
        approvalStatus: 'Not Required',
      },
    ],
    activityHistory: [
      {
        id: 'act-003',
        message: 'Deadline modified after carrier integration delay',
        actor: 'Omar Khan',
        date: format(addDays(today, -7), 'yyyy-MM-dd'),
      },
    ],
  },
  {
    id: 'proj-003',
    projectCode: 'FIN-3207',
    name: 'Quarter Close Control Center',
    description:
      'Centralize close milestones, document collection, and department readiness for finance leadership.',
    projectType: 'Internal Tool',
    projectTemplate: 'Blank Project',
    projectCategory: 'Compliance',
    tags: ['finance', 'quarter-close'],
    clientName: 'Laura Chen',
    clientCompany: 'Apex Finance Group',
    clientEmail: 'laura.chen@apexfinance.example',
    clientPhone: '+1 555 013 9812',
    clientLocation: 'Boston, USA',
    projectOwner: 'Priya Shah',
    stakeholders: ['Meera Iyer'],
    deadlineType: 'Fixed Deadline',
    budget: 94000,
    developmentCost: 60000,
    resourceCost: 20000,
    department: 'Finance',
    owner: 'Priya Shah',
    manager: 'Meera Iyer',
    startDate: format(addDays(today, -20), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 44), 'yyyy-MM-dd'),
    priority: 'Medium',
    status: 'Planned',
    approvalRequired: false,
    approvalStatus: 'Not Required',
    closureApprovalRequired: true,
    closureStatus: 'Not Required',
    progress: 28,
    teamMembers: ['Priya Shah', 'Meera Iyer', 'Nikhil Jain'],
    team: [
      { name: 'Meera Iyer', role: 'Project Manager', permissions: ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'] },
      { name: 'Nikhil Jain', role: 'Developer', permissions: ['view_project','create_task','edit_task','upload_files'] },
    ],
    techStack: emptyTechStack,
    repository: emptyRepo,
    modules: [],
    sprints: [],
    risks: [],
    communication: emptyCommunication,
    tasks: [],
    requirementDocument: null,
    notes: 'Scope approved. Waiting for tax checklist confirmation.',
    comments: [],
    attachments: [],
    milestones: [
      {
        id: 'ms-005',
        title: 'Close checklist sign-off',
        dueDate: format(addDays(today, 10), 'yyyy-MM-dd'),
        status: 'Pending',
        approvalRequired: true,
        approvalStatus: 'Not Required',
      },
      {
        id: 'ms-006',
        title: 'Leadership dashboard preview',
        dueDate: format(addDays(today, 29), 'yyyy-MM-dd'),
        status: 'Pending',
        approvalRequired: false,
        approvalStatus: 'Not Required',
      },
    ],
    activityHistory: [
      {
        id: 'act-004',
        message: 'Project created',
        actor: 'Priya Shah',
        date: format(addDays(today, -20), 'yyyy-MM-dd'),
      },
    ],
  },
  {
    id: 'proj-004',
    projectCode: 'IT-9044',
    name: 'Employee Portal Security Upgrade',
    description:
      'Upgrade access controls, audit visibility, and document permissions for the employee self-service portal.',
    projectType: 'Web Application',
    projectTemplate: 'Implementation',
    projectCategory: 'Internal',
    tags: ['security', 'portal', 'access-control'],
    clientName: 'Marcus Reed',
    clientCompany: 'Internal IT Steering Committee',
    clientEmail: 'marcus.reed@company.example',
    clientPhone: '+1 555 019 4430',
    clientLocation: 'San Francisco, USA',
    projectOwner: 'David Kim',
    stakeholders: ['Ananya Rao'],
    deadlineType: 'Fixed Deadline',
    budget: 180000,
    developmentCost: 120000,
    resourceCost: 40000,
    department: 'IT',
    owner: 'David Kim',
    manager: 'Ananya Rao',
    startDate: format(addDays(today, -88), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    priority: 'Critical',
    status: 'In Progress',
    approvalRequired: true,
    approvalStatus: 'Approved',
    closureApprovalRequired: true,
    closureStatus: 'Not Required',
    progress: 86,
    teamMembers: ['David Kim', 'Ananya Rao', 'Fatima Noor', 'Luis Martin'],
    team: [
      { name: 'Ananya Rao', role: 'Project Manager', permissions: ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'] },
      { name: 'Fatima Noor', role: 'Developer', permissions: ['view_project','create_task','edit_task','upload_files'] },
      { name: 'Luis Martin', role: 'DevOps Engineer', permissions: ['view_project','edit_task','upload_files','approve_release'] },
    ],
    techStack: { frontend: ['React'], backend: ['Spring Boot'], database: ['PostgreSQL'], other: ['Docker','Kubernetes'] },
    repository: { gitUrl: 'https://github.com/org/portal-security', branchStrategy: 'Git Flow', devUrl: '', testingUrl: '', productionUrl: '' },
    modules: [],
    sprints: [],
    risks: [],
    communication: emptyCommunication,
    tasks: [],
    requirementDocument: {
      id: 'req-004',
      name: 'security-upgrade-requirements.docx',
      type: 'Document',
      size: '780 KB',
      uploadedBy: 'David Kim',
      uploadedAt: format(addDays(today, -79), 'yyyy-MM-dd'),
    },
    notes: 'Permission matrix is under final regression testing.',
    comments: [
      {
        id: 'com-004',
        author: 'Ananya Rao',
        message: 'Security review notes are ready for final validation.',
        date: format(addDays(today, -2), 'yyyy-MM-dd'),
      },
    ],
    attachments: [
      {
        id: 'att-003',
        name: 'security-checklist.docx',
        type: 'Document',
        size: '520 KB',
        uploadedBy: 'David Kim',
        uploadedAt: format(addDays(today, -13), 'yyyy-MM-dd'),
      },
    ],
    milestones: [
      {
        id: 'ms-007',
        title: 'Role matrix verification',
        dueDate: format(addDays(today, 2), 'yyyy-MM-dd'),
        status: 'In Progress',
        approvalRequired: true,
        approvalStatus: 'Not Required',
      },
      {
        id: 'ms-008',
        title: 'Production readiness review',
        dueDate: format(addDays(today, 5), 'yyyy-MM-dd'),
        status: 'Pending',
        approvalRequired: true,
        approvalStatus: 'Not Required',
      },
    ],
    activityHistory: [
      {
        id: 'act-005',
        message: 'File uploaded: security-checklist.docx',
        actor: 'David Kim',
        date: format(addDays(today, -13), 'yyyy-MM-dd'),
      },
    ],
  },
  {
    id: 'proj-005',
    projectCode: 'HR-6110',
    name: 'Hiring Workflow Standardization',
    description:
      'Create a consistent intake, interview, offer, and onboarding workflow for department hiring plans.',
    projectType: 'Internal Tool',
    projectTemplate: 'Internal Operations',
    projectCategory: 'Operations',
    tags: ['hr', 'hiring', 'workflow'],
    clientName: 'Helen Brooks',
    clientCompany: 'People Operations',
    clientEmail: 'helen.brooks@company.example',
    clientPhone: '+1 555 015 1008',
    clientLocation: 'Austin, USA',
    projectOwner: 'Priya Shah',
    stakeholders: [],
    deadlineType: 'Flexible',
    budget: 52000,
    developmentCost: 30000,
    resourceCost: 15000,
    department: 'HR',
    owner: 'Priya Shah',
    manager: 'Omar Khan',
    startDate: format(addDays(today, -120), 'yyyy-MM-dd'),
    endDate: format(addDays(today, -28), 'yyyy-MM-dd'),
    priority: 'Low',
    status: 'Completed',
    approvalRequired: false,
    approvalStatus: 'Not Required',
    closureApprovalRequired: true,
    closureStatus: 'Approved',
    progress: 100,
    teamMembers: ['Priya Shah', 'Omar Khan', 'Riya Menon'],
    team: [
      { name: 'Omar Khan', role: 'Project Manager', permissions: ['view_project','create_task','assign_task','edit_task','delete_task','upload_files','approve_release'] },
      { name: 'Riya Menon', role: 'Developer', permissions: ['view_project','create_task','edit_task','upload_files'] },
    ],
    techStack: emptyTechStack,
    repository: emptyRepo,
    modules: [],
    sprints: [],
    risks: [],
    communication: emptyCommunication,
    tasks: [],
    requirementDocument: null,
    notes: 'Released to HR operations with adoption dashboard.',
    comments: [],
    attachments: [],
    milestones: [
      {
        id: 'ms-009',
        title: 'Go-live',
        dueDate: format(addDays(today, -28), 'yyyy-MM-dd'),
        status: 'Done',
        approvalRequired: false,
        approvalStatus: 'Not Required',
      },
    ],
    activityHistory: [
      {
        id: 'act-006',
        message: 'Project completed',
        actor: 'Priya Shah',
        date: format(addDays(today, -28), 'yyyy-MM-dd'),
      },
    ],
  },
]
